apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: leviora-website

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/leviora-ai/leviora-website
    newTag: latest
  - name: ghcr.io/leviora-ai/leviora-website-api
    newTag: latest

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: leviora-marketing
      app.kubernetes.io/managed-by: kustomize
